# Generated by Django 4.2.16 on 2024-11-29 05:54

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import Group, Permission


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('feed', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('bedroom_count', models.PositiveIntegerField()),
                ('review_score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('usd_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('images', models.JSONField(default=list)),
                ('amenities', models.JSONField(default=list)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_type', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('state_abbr', models.CharField(blank=True, max_length=3)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='LocalizeAccommodation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('policy', models.JSONField(default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.accommodation')),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
