# Generated by Django 4.2.16 on 2024-12-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_property_owner_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images/'),
        ),
    ]
