# Generated by Django 4.2.16 on 2024-12-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_accommodation_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
