# Generated by Django 4.2.16 on 2024-12-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_accommodationimage'),
    ]

    operations = [
        # Step 3.1: Rename the original table
        migrations.RunSQL("""
            ALTER TABLE inventory_accommodation RENAME TO inventory_accommodation_temp;
        """),

        # Step 3.2: Create the new partitioned table
        migrations.RunSQL("""
            CREATE TABLE inventory_accommodation (
                id VARCHAR(20) NOT NULL,
                feed SMALLINT NOT NULL,
                title VARCHAR(100) NOT NULL,
                country_code VARCHAR(2) NOT NULL,
                bedroom_count INT NOT NULL,
                review_score NUMERIC(3, 1) DEFAULT 0,
                usd_rate NUMERIC(10, 2),
                center GEOGRAPHY(POINT, 4326),
                images JSONB DEFAULT '[]',
                image_file VARCHAR(100),
                amenities JSONB DEFAULT '[]',
                user_id INT NOT NULL,
                location_id VARCHAR(20) NOT NULL,
                published BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP DEFAULT NOW(),
                updated_at TIMESTAMP DEFAULT NOW(),
                PRIMARY KEY (id, feed)
            ) PARTITION BY LIST (feed);
        """),

        # Step 3.3: Create the partitions
        migrations.RunSQL("""
            CREATE TABLE accommodation_feed_1 PARTITION OF inventory_accommodation FOR VALUES IN (1);
            CREATE TABLE accommodation_feed_2 PARTITION OF inventory_accommodation FOR VALUES IN (2);
            CREATE TABLE accommodation_feed_3 PARTITION OF inventory_accommodation FOR VALUES IN (3);
            CREATE TABLE accommodation_feed_4 PARTITION OF inventory_accommodation FOR VALUES IN (4);
        """),

        # Step 3.4: Migrate data from the temporary table
        migrations.RunSQL("""
            INSERT INTO inventory_accommodation (
                id, feed, title, country_code, bedroom_count, review_score, usd_rate,
                center, images, amenities, user_id, location_id, published, created_at, updated_at
            )
            SELECT
                id, feed, title, country_code, bedroom_count, review_score, usd_rate,
                center, images, amenities, user_id, location_id, published, created_at, updated_at
            FROM inventory_accommodation_temp;
        """),

        # Step 3.5: Drop the temporary table
        migrations.RunSQL("""
            DROP TABLE inventory_accommodation_temp;
        """),
    ]
