# Generated by Django 4.2.16 on 2024-12-04 16:12

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_change_center_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0), srid=4326),
            preserve_default=False,
        ),
    ]
